// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIPpzmeYgwgsO6NRIb7uyx_LGHCmuqqOc',
    appId: '1:105177709047:web:3b29f95ab87483352056f2',
    messagingSenderId: '105177709047',
    projectId: 'playschool-fae76',
    authDomain: 'playschool-fae76.firebaseapp.com',
    storageBucket: 'playschool-fae76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5MJu_rnghcwQQNxbCDaAK3L2Fc6iJls',
    appId: '1:105177709047:android:3eed7387d0ac27002056f2',
    messagingSenderId: '105177709047',
    projectId: 'playschool-fae76',
    storageBucket: 'playschool-fae76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd5DVXc3UolDokL8QJoDbz0Q6hcZnsQEs',
    appId: '1:105177709047:ios:f36a2191b1b2c0e12056f2',
    messagingSenderId: '105177709047',
    projectId: 'playschool-fae76',
    storageBucket: 'playschool-fae76.appspot.com',
    iosClientId: '105177709047-jsaheffhel6lukrut8fvdt02hqfbs6id.apps.googleusercontent.com',
    iosBundleId: 'com.example.playschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd5DVXc3UolDokL8QJoDbz0Q6hcZnsQEs',
    appId: '1:105177709047:ios:f36a2191b1b2c0e12056f2',
    messagingSenderId: '105177709047',
    projectId: 'playschool-fae76',
    storageBucket: 'playschool-fae76.appspot.com',
    iosClientId: '105177709047-jsaheffhel6lukrut8fvdt02hqfbs6id.apps.googleusercontent.com',
    iosBundleId: 'com.example.playschool',
  );
}
